kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
    - go vet
    - go test -v -cover
  when:
    event:
    - push
    - pull_request

- name: build
  image: golang
  commands:
    - go build
  when:
    event:
    - push
    - pull_request

- name: docker-push
  image: plugins/docker
  settings:
    repo: guangbo/drone-go-example
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
  when:
    branch: master
    event:
    - push
    - pull_request

- name: k8s-deploy
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server:
      from_secret: KUBERNETES_SERVER
    kubernetes_token:
      from_secret: KUBERNETES_TOKEN
    namespace: default
    deployment: drone-with-go
    repo: guangbo/drone-ci-demo
    container: drone-with-go
  when:
    event: push
