kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
    - go vet
    - go test -v -cover
  when:
    event:
    - push
    - pull_request

- name: build
  image: golang
  commands:
    - go build
  when:
    event:
    - push
    - pull_request

- name: docker
  image: plugins/docker
  settings:
    repo: guangbo/drone-go-example
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    when:
      event: tag
