kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
    - go vet
    - go test -v -cover
  when:
    event:
    - push
    - pull_request
- name: build
  image: golang
  commands:
    - go build
  when:
    event:
    - push
    - pull_request
